"""
agent.py
--------
The main LangGraph agent. It takes a natural language question,
converts it to SQL using Llama 3 8B (running locally via Ollama),
runs the query against SQLite, and returns results.

LangGraph works like a flowchart: you define NODES (steps) and EDGES
(arrows between steps). The agent flows through them automatically.

Flow:
  [START] → schema_loader → sql_generator → sql_validator → sql_runner → result_formatter → [END]

IMPORTANT: Ollama must be running before you use this agent.
  1. Install Ollama: https://ollama.com  (free app for Mac)
  2. Open Terminal and run: ollama pull llama3   (downloads model once, ~4.7GB)
  3. Keep Ollama running in the background (it starts automatically after install)
  That's it — no API key needed, everything runs on your MacBook.
"""

import sqlite3
import re
from typing import TypedDict, Optional

# LangGraph imports
from langgraph.graph import StateGraph, END

# Ollama runs Llama 3 locally and exposes an OpenAI-compatible API
# at http://localhost:11434 — so we use the openai library but pointed
# at localhost instead of OpenAI's servers. No API key needed.
from openai import OpenAI

# Our evaluation logger (records what worked, what broke)
from eval_logger import log_turn

# ---------------------------------------------------------------------------
# Ollama client setup
# base_url → your local machine (Ollama listens here by default)
# api_key  → "ollama" is a placeholder; Ollama doesn't check it
# ---------------------------------------------------------------------------
OLLAMA_CLIENT = OpenAI(
    base_url = "http://localhost:11434/v1",
    api_key  = "ollama",
)

LLAMA_MODEL = "llama3"   # matches the name you pulled: ollama pull llama3


# ---------------------------------------------------------------------------
# 1. STATE — the "memory" that flows between every node
#    TypedDict means: a dictionary where every key has a declared type.
# ---------------------------------------------------------------------------
class AgentState(TypedDict):
    question:            str            # the user's natural language question
    schema:              str            # the DB schema injected into the prompt
    sql_query:           str            # SQL generated by Llama 3
    sql_error:           Optional[str]  # error from running the SQL (None = success)
    raw_results:         list           # raw rows from the database
    final_answer:        str            # human-readable answer shown to the user
    hallucination_flags: list           # warnings about suspicious SQL


# ---------------------------------------------------------------------------
# 2. SCHEMA LOADER NODE
#    Reads the database structure and injects it into the prompt.
#    This is the single most important guardrail against hallucination —
#    Llama 3 can't invent column names if we show it the real ones first.
# ---------------------------------------------------------------------------
def schema_loader(state: AgentState) -> AgentState:
    """
    Opens the SQLite DB and reads the CREATE TABLE statements.
    The schema text is added to state so later nodes can use it.
    """
    conn   = sqlite3.connect("data/nyc_taxi.db")
    cursor = conn.cursor()

    # sqlite_master holds the CREATE TABLE SQL for every table
    cursor.execute("SELECT name, sql FROM sqlite_master WHERE type='table'")
    tables = cursor.fetchall()
    conn.close()

    schema_text = ""
    for table_name, create_sql in tables:
        schema_text += f"Table: {table_name}\n{create_sql}\n\n"

    state["schema"] = schema_text
    return state


# ---------------------------------------------------------------------------
# 3. SQL GENERATOR NODE
#    Sends the question + schema to Llama 3 running on your Mac via Ollama.
#
#    Key difference from GPT-4: Llama 3 8B needs more explicit instructions.
#    It tends to add markdown formatting and short explanations around the SQL,
#    so we aggressively strip those out after the response.
# ---------------------------------------------------------------------------
def sql_generator(state: AgentState) -> AgentState:
    """
    Calls Llama 3 (via Ollama) with the schema and question.
    Returns only the SQL — strips any formatting Llama adds around it.
    """

    system_prompt = """You are a SQL expert. You only output raw SQL queries, nothing else.

RULES — follow exactly:
- Output ONLY the SQL query, no explanations, no comments
- Do NOT use markdown formatting or backticks
- Use only the columns and tables shown in the schema
- Only write SELECT statements — never UPDATE, DELETE, DROP, INSERT
- If the question is unanswerable, output exactly: SELECT 'cannot answer'

SCOPE RULE — very important:
- When a question asks about patterns across ALL data (e.g. "which day",
  "which borough", "which vendor", "do people tip more on") do NOT add
  any WHERE clause filtering by specific dates unless the user explicitly
  mentions a specific date or time period in their question.
- Aggregate across the full dataset unless told otherwise.

THIS IS SQLITE — NOT POSTGRESQL. These SQLite-specific rules are mandatory:

For date filtering:
  strftime('%Y', pickup_datetime) = '2023'
  strftime('%m', pickup_datetime) = '01'

For trip duration in minutes:
  (strftime('%s', dropoff_datetime) - strftime('%s', pickup_datetime)) / 60.0

For day of week — ALWAYS use this exact CASE statement to show day names:
  CASE strftime('%w', pickup_datetime)
    WHEN '0' THEN 'Sunday'
    WHEN '1' THEN 'Monday'
    WHEN '2' THEN 'Tuesday'
    WHEN '3' THEN 'Wednesday'
    WHEN '4' THEN 'Thursday'
    WHEN '5' THEN 'Friday'
    WHEN '6' THEN 'Saturday'
  END AS day_of_week

For hour of day:
  strftime('%H', pickup_datetime)

NEVER use EXTRACT(), DATE_PART(), EPOCH, INTERVAL, or any PostgreSQL syntax.
NEVER use DATEDIFF() — that is MySQL syntax, not SQLite.
"""

    user_message = f"""Schema:
{state['schema']}

Question: {state['question']}

SQL:"""

    response = OLLAMA_CLIENT.chat.completions.create(
        model    = LLAMA_MODEL,
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_message},
        ],
        temperature = 0,
        max_tokens  = 300,
    )

    sql = response.choices[0].message.content.strip()

    sql = re.sub(r"```sql\s*", "", sql, flags=re.IGNORECASE)
    sql = re.sub(r"```\s*",    "", sql)
    match = re.search(r"\bSELECT\b", sql, re.IGNORECASE)
    if match:
        sql = sql[match.start():]
    sql = re.split(r";\s*\n", sql)[0]

    state["sql_query"]   = sql.strip()
    state["sql_error"]   = None
    state["raw_results"] = []
    return state

# ---------------------------------------------------------------------------
# 4. SQL VALIDATOR NODE — your guardrails layer
#    Checks for dangerous commands and hallucinated column names BEFORE
#    touching the database.
#
#    Why this matters for Llama 3 8B specifically:
#    The model was trained on the full NYC TLC taxi dataset docs, which have
#    many more columns than our simplified schema. It will confidently use
#    columns like 'pickup_latitude' or 'rate_code' that don't exist in our DB.
#    This node catches those before they cause confusing SQL errors.
# ---------------------------------------------------------------------------
HALLUCINATION_PATTERNS = [
    # --- Dangerous write commands ---
    (r"\bDROP\b",    "DANGER: query contains DROP — would delete data"),
    (r"\bDELETE\b",  "DANGER: query contains DELETE — would remove rows"),
    (r"\bINSERT\b",  "DANGER: query contains INSERT — would add rows"),
    (r"\bUPDATE\b",  "DANGER: query contains UPDATE — would modify rows"),
    (r"\bEXEC\b",    "DANGER: query contains EXEC — potential SQL injection"),
    # --- Columns from the real NYC TLC dataset that don't exist in our DB ---
    # Llama 3 knows these from training and will use them confidently
    (r"\btip_percentage\b",   "HALLUCINATION: 'tip_percentage' does not exist in schema"),
    (r"\bduration_minutes\b", "HALLUCINATION: 'duration_minutes' does not exist in schema"),
    (r"\brate_code\b",        "HALLUCINATION: 'rate_code' does not exist in schema"),
    (r"\bpickup_longitude\b", "HALLUCINATION: 'pickup_longitude' does not exist in schema"),
    (r"\bpickup_latitude\b",  "HALLUCINATION: 'pickup_latitude' does not exist in schema"),
    (r"\bdropoff_longitude\b","HALLUCINATION: 'dropoff_longitude' does not exist in schema"),
    (r"\bdropoff_latitude\b", "HALLUCINATION: 'dropoff_latitude' does not exist in schema"),
    (r"\btrip_type\b",        "HALLUCINATION: 'trip_type' does not exist in schema"),
    (r"\bstore_and_fwd\b",    "HALLUCINATION: 'store_and_fwd' does not exist in schema"),
    (r"\bsurcharge\b",        "HALLUCINATION: 'surcharge' does not exist in schema"),
    (r"\bmta_tax\b",          "HALLUCINATION: 'mta_tax' does not exist in schema"),
    (r"\btolls_amount\b",     "HALLUCINATION: 'tolls_amount' does not exist in schema"),
]

def sql_validator(state: AgentState) -> AgentState:
    """
    Scans the SQL for dangerous patterns and hallucinated column names.
    Blocks execution if dangerous. Records all flags for the eval log.
    """
    flags = []

    for pattern, message in HALLUCINATION_PATTERNS:
        if re.search(pattern, state["sql_query"], re.IGNORECASE):
            flags.append(message)

    state["hallucination_flags"] = flags

    # Block dangerous queries before they reach the database
    if any("DANGER" in f for f in flags):
        state["sql_error"]    = "Blocked: query contains dangerous commands."
        state["final_answer"] = f"Query was blocked for safety.\nFlags:\n" + "\n".join(flags)

    return state


# ---------------------------------------------------------------------------
# 5. SQL RUNNER NODE
#    Executes the validated SQL against SQLite.
# ---------------------------------------------------------------------------
def sql_runner(state: AgentState) -> AgentState:
    """
    Runs the SQL and stores results.
    Captures errors so the eval logger can record what broke.
    """
    if state.get("sql_error"):
        return state  # skip if already blocked

    try:
        conn   = sqlite3.connect("data/nyc_taxi.db")
        cursor = conn.cursor()

        cursor.execute(state["sql_query"])
        rows         = cursor.fetchall()
        column_names = [desc[0] for desc in cursor.description] if cursor.description else []
        conn.close()

        state["raw_results"] = {"columns": column_names, "rows": rows}

    except Exception as e:
        state["sql_error"]   = str(e)
        state["raw_results"] = {}

    return state


# ---------------------------------------------------------------------------
# 6. RESULT FORMATTER NODE
#    Formats raw DB rows into a readable answer, then logs the full turn.
# ---------------------------------------------------------------------------
def result_formatter(state: AgentState) -> AgentState:
    """
    Converts raw rows to a readable string.
    Calls eval_logger to save this turn to logs/eval_log.jsonl.
    """
    if state.get("sql_error") and not state["raw_results"]:
        answer = f"Error running query: {state['sql_error']}"
    else:
        data    = state["raw_results"]
        columns = data.get("columns", [])
        rows    = data.get("rows",    [])

        if not rows:
            answer = "Query ran successfully but returned no results."
        elif len(rows) == 1 and len(rows[0]) == 1:
            # Single-value result (COUNT, AVG, MAX, etc.)
            answer = f"Result: {rows[0][0]}"
        else:
            # Multi-row: format as a plain text table (max 20 rows shown)
            col_header = " | ".join(columns)
            separator  = "-" * len(col_header)
            row_lines  = [" | ".join(str(v) for v in row) for row in rows[:20]]
            answer     = f"{col_header}\n{separator}\n" + "\n".join(row_lines)
            if len(rows) > 20:
                answer += f"\n... ({len(rows) - 20} more rows not shown)"

    state["final_answer"] = answer

    # Log every turn automatically — this builds your eval dataset
    log_turn(
        question            = state["question"],
        sql_generated       = state["sql_query"],
        sql_error           = state.get("sql_error"),
        result_preview      = answer[:300],
        hallucination_flags = state.get("hallucination_flags", []),
    )

    return state


# ---------------------------------------------------------------------------
# 7. ROUTING FUNCTION
#    Decides whether to run the SQL or jump straight to the formatter.
# ---------------------------------------------------------------------------
def route_after_validation(state: AgentState) -> str:
    if state.get("sql_error"):
        return "result_formatter"   # blocked — skip runner
    return "sql_runner"             # safe to run


# ---------------------------------------------------------------------------
# 8. BUILD THE LANGGRAPH
# ---------------------------------------------------------------------------
def build_agent():
    """
    Wires all nodes together into a compiled LangGraph state machine.
    """
    graph = StateGraph(AgentState)

    graph.add_node("schema_loader",    schema_loader)
    graph.add_node("sql_generator",    sql_generator)
    graph.add_node("sql_validator",    sql_validator)
    graph.add_node("sql_runner",       sql_runner)
    graph.add_node("result_formatter", result_formatter)

    graph.set_entry_point("schema_loader")

    graph.add_edge("schema_loader", "sql_generator")
    graph.add_edge("sql_generator", "sql_validator")

    graph.add_conditional_edges(
        "sql_validator",
        route_after_validation,
        {
            "sql_runner":       "sql_runner",
            "result_formatter": "result_formatter",
        }
    )

    graph.add_edge("sql_runner",       "result_formatter")
    graph.add_edge("result_formatter", END)

    return graph.compile()


# ---------------------------------------------------------------------------
# 9. PUBLIC FUNCTION — the only thing main.py needs to call
# ---------------------------------------------------------------------------
def ask(question: str) -> dict:
    """
    Run a natural language question through the full LangGraph agent.
    Returns: question, sql_query, final_answer, hallucination_flags, sql_error
    """
    app = build_agent()

    initial_state: AgentState = {
        "question":            question,
        "schema":              "",
        "sql_query":           "",
        "sql_error":           None,
        "raw_results":         [],
        "final_answer":        "",
        "hallucination_flags": [],
    }

    final_state = app.invoke(initial_state)

    return {
        "question":            final_state["question"],
        "sql_query":           final_state["sql_query"],
        "final_answer":        final_state["final_answer"],
        "hallucination_flags": final_state["hallucination_flags"],
        "sql_error":           final_state["sql_error"],
    }
